/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.master.pm.gui;

import com.master.pm.dbal.ClubDB4O;
import com.master.pm.dbal.ManagerDB4O;
import com.master.pm.dbal.PlayerDB4O;
import com.master.pm.entity.Club;
import com.master.pm.entity.Manager;
import com.master.pm.entity.Player;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Win10 Pro
 */
public class index extends javax.swing.JFrame {

    private List<Manager> managers;
    private int indexManager;

    /**
     * Creates new form Player
     */
    public index() {
	initComponents();
	showPlayer();
	showManager();
	showClub();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManager = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jtxtManagerCountry = new javax.swing.JTextField();
        jtxtManagerActive = new javax.swing.JTextField();
        jtxtManagerId = new javax.swing.JTextField();
        jtxtManagerLastName = new javax.swing.JTextField();
        jtxtManagerClub = new javax.swing.JTextField();
        jtxtManagerDob = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAddManager = new javax.swing.JButton();
        jButtonUpdateManager = new javax.swing.JButton();
        jButtonDeleteManager = new javax.swing.JButton();
        jButtonRefreshManager = new javax.swing.JButton();
        jButtonClearManager = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxtManagerName = new javax.swing.JTextField();
        jtxtManagerFirstName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jtxtpos = new javax.swing.JTextField();
        jtxtcountry = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jtxtposInfo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtclub = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jtxtid = new javax.swing.JTextField();
        jtxtdob = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableClub = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButtonAddClub = new javax.swing.JButton();
        jButtonEditClub = new javax.swing.JButton();
        jButtonDeleteClub = new javax.swing.JButton();
        jButtonRefreshClub = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jtxtabbrClub = new javax.swing.JTextField();
        jtxtidClub = new javax.swing.JTextField();
        jtxtshortNameClub = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSearch = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jtxtPosSearch = new javax.swing.JTextField();
        jtxttoAgeSearch = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton_Search = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jtxtNameSearch = new javax.swing.JTextField();
        jtxtfromAgeSearch = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtxtCountrySearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "_id", "name", "firstName", "lastName", "club", "dob", "country", "active"
            }
        ));
        jTableManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableManagerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableManager);

        jLabel4.setText("club");
        jLabel4.setToolTipText("");

        jLabel8.setText("dob");
        jLabel8.setToolTipText("");

        jLabel6.setText("lastName");

        jLabel3.setText("active");

        jLabel5.setText("_id");
        jLabel5.setToolTipText("");

        jLabel2.setText("country");

        jButtonAddManager.setText("Add");
        jButtonAddManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddManagerActionPerformed(evt);
            }
        });

        jButtonUpdateManager.setText("Update");
        jButtonUpdateManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateManagerActionPerformed(evt);
            }
        });

        jButtonDeleteManager.setText("Delete");
        jButtonDeleteManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteManagerActionPerformed(evt);
            }
        });

        jButtonRefreshManager.setText("Refresh");
        jButtonRefreshManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshManagerActionPerformed(evt);
            }
        });

        jButtonClearManager.setText("Clear");
        jButtonClearManager.setName("jtxtClearManager"); // NOI18N
        jButtonClearManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClearManagerMouseClicked(evt);
            }
        });
        jButtonClearManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearManagerActionPerformed(evt);
            }
        });

        jLabel7.setText("name");
        jLabel7.setToolTipText("");

        jLabel16.setText("firstName");
        jLabel16.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtManagerActive, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtManagerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtManagerId, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(jtxtManagerName)
                                .addComponent(jtxtManagerFirstName))
                            .addComponent(jtxtManagerClub, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtManagerDob, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtManagerCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonAddManager, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearManager, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonUpdateManager, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteManager, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRefreshManager, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtManagerActive, jtxtManagerClub, jtxtManagerCountry, jtxtManagerDob, jtxtManagerId, jtxtManagerLastName});

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAddManager, jButtonClearManager, jButtonDeleteManager, jButtonRefreshManager, jButtonUpdateManager});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtManagerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtManagerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtManagerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtManagerClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtManagerDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtManagerCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtManagerActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddManager)
                    .addComponent(jButtonClearManager)
                    .addComponent(jButtonUpdateManager)
                    .addComponent(jButtonDeleteManager)
                    .addComponent(jButtonRefreshManager))
                .addGap(424, 424, 424))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAddManager, jButtonDeleteManager, jButtonRefreshManager, jButtonUpdateManager});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manager", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "country", "club", "dob", "pos", "posInfo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel11.setText("country");

        jLabel14.setText("pos");

        jLabel10.setText("name");

        jLabel15.setText("posInfo");

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel13.setText("dob");
        jLabel13.setToolTipText("");

        jLabel12.setText("club");
        jLabel12.setToolTipText("");

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel9.setText("player_id");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtposInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jtxtpos)
                            .addComponent(jtxtdob)
                            .addComponent(jtxtclub)
                            .addComponent(jtxtcountry)
                            .addComponent(jtxtname)
                            .addComponent(jtxtid)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRefresh)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdd, jButtonDelete, jButtonEdit, jButtonRefresh});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtclub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtposInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonRefresh)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Player", jPanel2);

        jTableClub.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "shortName", "abbr"
            }
        ));
        jScrollPane4.setViewportView(jTableClub);

        jButtonAddClub.setText("Add");
        jButtonAddClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddClubActionPerformed(evt);
            }
        });

        jButtonEditClub.setText("Edit");
        jButtonEditClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditClubActionPerformed(evt);
            }
        });

        jButtonDeleteClub.setText("Delete");
        jButtonDeleteClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteClubActionPerformed(evt);
            }
        });

        jButtonRefreshClub.setText("Refresh");
        jButtonRefreshClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshClubActionPerformed(evt);
            }
        });

        jLabel19.setText("abbr");

        jLabel18.setText("shortName");

        jLabel17.setText("club_id");
        jLabel17.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtabbrClub, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jtxtshortNameClub)
                            .addComponent(jtxtidClub)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButtonAddClub, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditClub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteClub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRefreshClub)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAddClub, jButtonDeleteClub, jButtonEditClub, jButtonRefreshClub});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtxtidClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtshortNameClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtabbrClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddClub, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonRefreshClub)
                        .addComponent(jButtonDeleteClub)
                        .addComponent(jButtonEditClub)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Club", jPanel3);

        jTableSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Country", "Age", "Pos"
            }
        ));
        jScrollPane2.setViewportView(jTableSearch);

        jLabel23.setText("Age");

        jLabel22.setText("Position");

        jLabel25.setText("-");

        jButton_Search.setText("Search");
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        jLabel21.setText("Name");

        jLabel20.setText("Country");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addGap(51, 51, 51)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtNameSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jtxtCountrySearch))
                .addGap(63, 63, 63)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jtxtfromAgeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxttoAgeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtPosSearch))
                .addGap(82, 82, 82)
                .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jtxtfromAgeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jtxttoAgeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jtxtCountrySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtxtPosSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Player Search", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddManagerActionPerformed
	try {
	    if (!jtxtManagerId.getText().isEmpty() || !jtxtManagerLastName.getText().isEmpty() || !jtxtManagerClub.getText().isEmpty()
			    || !jtxtManagerDob.getText().isEmpty() || !jtxtManagerCountry.getText().isEmpty() || !jtxtManagerActive.getText().isEmpty()) {
		Manager manager = new Manager();
		manager.setFirstName(jtxtManagerId.getText());
		manager.setLastName(jtxtManagerLastName.getText());
		manager.setClub(jtxtManagerClub.getText());
		manager.setDob(Integer.parseInt(jtxtManagerDob.getText()));
		manager.setCountry(jtxtManagerCountry.getText());
		manager.setActive(Boolean.parseBoolean(jtxtManagerActive.getText()));
		ManagerDB4O.INST.storeManager(manager);
		DefaultTableModel model = (DefaultTableModel) jTableManager.getModel();
		model.setRowCount(0);
		JOptionPane.showMessageDialog(null, "Insert sucessful!");
	    }

	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e);
	}
    }//GEN-LAST:event_jButtonAddManagerActionPerformed

    private void jButtonUpdateManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateManagerActionPerformed
	try {
	    if (!jtxtManagerId.getText().isEmpty() || !jtxtManagerLastName.getText().isEmpty() || !jtxtManagerName.getText().isEmpty()
			    || !jtxtManagerDob.getText().isEmpty() || !jtxtManagerCountry.getText().isEmpty() || !jtxtManagerActive.getText().isEmpty()) {
		Manager manager = managers.get(indexManager);
		manager.setActive(Boolean.parseBoolean(jtxtManagerActive.getText()));
		manager.setClub(jtxtManagerClub.getText());
		manager.setDob(Long.parseLong(jtxtManagerDob.getText()));
		manager.setFirstName(jtxtManagerFirstName.getText());
		manager.setId(jtxtManagerId.getText());
		manager.setLastName(jtxtManagerLastName.getText());
		manager.setName(jtxtManagerName.getText());

		ManagerDB4O.INST.updateManagerById(manager);

		JOptionPane.showMessageDialog(null, "Update sucessful!");
	    }
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e);
	}
    }//GEN-LAST:event_jButtonUpdateManagerActionPerformed

    private void jButtonDeleteManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteManagerActionPerformed
	try {
	    if (!jtxtManagerId.getText().isEmpty()) {
		Manager manager = managers.get(indexManager);
		ManagerDB4O.INST.deleteManagerById(manager);
		showManager();
		JOptionPane.showMessageDialog(null, "Deleted sucessful!");
	    }
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e);
	}
    }//GEN-LAST:event_jButtonDeleteManagerActionPerformed

    private void jButtonRefreshManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshManagerActionPerformed
	this.showManager();

    }//GEN-LAST:event_jButtonRefreshManagerActionPerformed

    private void jButtonAddClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddClubActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddClubActionPerformed

    private void jButtonEditClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditClubActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditClubActionPerformed

    private void jButtonDeleteClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteClubActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteClubActionPerformed

    private void jButtonRefreshClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshClubActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefreshClubActionPerformed

    private void jTableManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableManagerMouseClicked
	indexManager = jTableManager.getSelectedRow();
	TableModel model = jTableManager.getModel();
	jtxtManagerId.setText(model.getValueAt(indexManager, 0).toString());
	jtxtManagerName.setText(model.getValueAt(indexManager, 1).toString());
	jtxtManagerFirstName.setText(model.getValueAt(indexManager, 2).toString());
	jtxtManagerLastName.setText(model.getValueAt(indexManager, 3).toString());
	jtxtManagerClub.setText(model.getValueAt(indexManager, 4).toString());
	jtxtManagerDob.setText(model.getValueAt(indexManager, 5).toString());
	jtxtManagerCountry.setText(model.getValueAt(indexManager, 6).toString());
	jtxtManagerActive.setText(model.getValueAt(indexManager, 7).toString());
    }//GEN-LAST:event_jTableManagerMouseClicked

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
	jtxtid.setText("");
	jtxtname.setText("");
	jtxtcountry.setText("");
	jtxtclub.setText("");
	jtxtdob.setText("");
	jtxtpos.setText("");
	jtxtposInfo.setText("");
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
	try {
	    if (!jtxtid.getText().isEmpty()) {
		Player player = new Player();
		player.setId(jtxtid.getText());
		PlayerDB4O.INST.deletePlayerById(player);

		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		model.setRowCount(0);
		showPlayer();
		JOptionPane.showMessageDialog(null, "Deleted sucessful!");
	    }
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e);
	}
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
	try {
	    if (!jtxtdob.getText().isEmpty() || !jtxtpos.getText().isEmpty() || !jtxtposInfo.getText().isEmpty()
			    || !jtxtname.getText().isEmpty() || !jtxtclub.getText().isEmpty() || !jtxtid.getText().isEmpty()) {
		java.util.List<Player> listResult = new ArrayList<>();
		Player player = new Player();
		player.setId(jtxtid.getText());
		player.setName(jtxtname.getText());
		player.setCountry(jtxtcountry.getText());
		player.setDob(Integer.parseInt(jtxtdob.getText()));
		player.setClub(jtxtclub.getText());
		player.setPos(jtxtpos.getText());
		player.setPosInfo(jtxtposInfo.getText());
		PlayerDB4O.INST.updatePlayerById(player);

		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		model.setRowCount(0);
		showPlayer();

		JOptionPane.showMessageDialog(null, "Update sucessful!");
	    }
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e);
	}
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
	try {
	    if (!jtxtdob.getText().isEmpty() || !jtxtpos.getText().isEmpty() || !jtxtposInfo.getText().isEmpty()
			    || !jtxtname.getText().isEmpty() || !jtxtclub.getText().isEmpty() || !jtxtid.getText().isEmpty()) {
		java.util.List<Player> listResult = new ArrayList<>();
		Player player = new Player();
		player.setId(jtxtid.getText());
		player.setName(jtxtname.getText());
		player.setCountry(jtxtcountry.getText());
		player.setDob(Integer.parseInt(jtxtdob.getText()));
		player.setClub(jtxtclub.getText());
		player.setPos(jtxtpos.getText());
		player.setPosInfo(jtxtposInfo.getText());
		PlayerDB4O.INST.storePlayer(player);
		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		model.setRowCount(0);
		showPlayer();
		JOptionPane.showMessageDialog(null, "Insert sucessful!");
	    }
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e);
	}
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
	int i = jTable1.getSelectedRow();
	TableModel model = jTable1.getModel();
	jtxtid.setText(model.getValueAt(i, 0).toString());
	jtxtname.setText(model.getValueAt(i, 1).toString());
	jtxtcountry.setText(model.getValueAt(i, 2).toString());
	jtxtclub.setText(model.getValueAt(i, 3).toString());
	jtxtdob.setText(model.getValueAt(i, 4).toString());
	jtxtpos.setText(model.getValueAt(i, 5).toString());
	jtxtposInfo.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
	java.util.List<Player> listResult = new ArrayList<>();
	int fromAge = -1;
	int toAge = -1;
	if (!jtxtfromAgeSearch.getText().isEmpty()) {
	    fromAge = Integer.parseInt(jtxtfromAgeSearch.getText());
	}

	if (!jtxttoAgeSearch.getText().isEmpty()) {
	    toAge = Integer.parseInt(jtxttoAgeSearch.getText());
	}

	listResult = PlayerDB4O.INST.searchPlayersByAdvancedQuery(jtxtNameSearch.getText(), jtxtCountrySearch.getText(), jtxtPosSearch.getText(),
			fromAge, toAge);

	System.out.println(listResult);
	DateFormat df = new SimpleDateFormat("dd/MM/YYYY");

	DefaultTableModel model = (DefaultTableModel) jTableSearch.getModel();
	model.setRowCount(0);
	Object[] row = new Object[4];

	for (int i = 0; i < listResult.size(); i++) {
	    row[0] = listResult.get(i).getName();
	    row[1] = listResult.get(i).getCountry();

	    row[2] = df.format(new Date((long) (listResult.get(i).getDob()) * 1000L));
	    row[3] = listResult.get(i).getPos();
	    model.addRow(row);
	}
	jTableSearch.setModel(model);
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jButtonClearManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearManagerActionPerformed
	jtxtManagerId.setText("");
	jtxtManagerLastName.setText("");
	jtxtManagerCountry.setText("");
	jtxtManagerClub.setText("");
	jtxtManagerDob.setText("");
	jtxtManagerCountry.setText("");
	jtxtManagerActive.setText("");
	jtxtManagerName.setText("");
	jtxtManagerFirstName.setText("");
    }//GEN-LAST:event_jButtonClearManagerActionPerformed

    private void jButtonClearManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClearManagerMouseClicked
	// TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearManagerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new index().setVisible(true);
	    }
	});
    }

    public void showPlayer() {
	java.util.List<Player> listResult = new ArrayList<>();
	listResult = PlayerDB4O.INST.listAllPlayers();
	DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
	model.setRowCount(0);
	Object[] row = new Object[7];
	for (int i = 0; i < listResult.size(); i++) {
	    row[0] = listResult.get(i).getId();
	    row[1] = listResult.get(i).getName();
	    row[2] = listResult.get(i).getCountry();
	    row[3] = listResult.get(i).getClub();
	    row[4] = listResult.get(i).getDob();
	    row[5] = listResult.get(i).getPos();
	    row[6] = listResult.get(i).getPosInfo();
	    model.addRow(row);
	}
	jTable1.setModel(model);
    }

    public void showManager() {
	managers = ManagerDB4O.INST.listAllManagers();
	DefaultTableModel model = (DefaultTableModel) jTableManager.getModel();
	model.setRowCount(0);
	Object[] row = new Object[8];
	for (int i = 0; i < managers.size(); i++) {
	    row[0] = managers.get(i).getId();
	    row[1] = managers.get(i).getName();
	    row[2] = managers.get(i).getFirstName();
	    row[3] = managers.get(i).getLastName();
	    row[4] = managers.get(i).getClub();
	    row[5] = managers.get(i).getDob();
	    row[6] = managers.get(i).getCountry();
	    row[7] = managers.get(i).isActive();
	    model.addRow(row);
	}
	jTableManager.setModel(model);
    }

    public void showClub() {
	java.util.List<Club> listResult = new ArrayList<>();
	listResult = ClubDB4O.INST.listAllClubs();
	DefaultTableModel model = (DefaultTableModel) jTableClub.getModel();
	model.setRowCount(0);
	Object[] row = new Object[3];
	for (int i = 0; i < listResult.size(); i++) {
	    row[0] = listResult.get(i).getId();
	    row[1] = listResult.get(i).getShortName();
	    row[2] = listResult.get(i).getAbbr();
	    model.addRow(row);
	}
	jTableClub.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddClub;
    private javax.swing.JButton jButtonAddManager;
    private javax.swing.JButton jButtonClearManager;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDeleteClub;
    private javax.swing.JButton jButtonDeleteManager;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonEditClub;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonRefreshClub;
    private javax.swing.JButton jButtonRefreshManager;
    private javax.swing.JButton jButtonUpdateManager;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableClub;
    private javax.swing.JTable jTableManager;
    private javax.swing.JTable jTableSearch;
    private javax.swing.JTextField jtxtCountrySearch;
    private javax.swing.JTextField jtxtManagerActive;
    private javax.swing.JTextField jtxtManagerClub;
    private javax.swing.JTextField jtxtManagerCountry;
    private javax.swing.JTextField jtxtManagerDob;
    private javax.swing.JTextField jtxtManagerFirstName;
    private javax.swing.JTextField jtxtManagerId;
    private javax.swing.JTextField jtxtManagerLastName;
    private javax.swing.JTextField jtxtManagerName;
    private javax.swing.JTextField jtxtNameSearch;
    private javax.swing.JTextField jtxtPosSearch;
    private javax.swing.JTextField jtxtabbrClub;
    private javax.swing.JTextField jtxtclub;
    private javax.swing.JTextField jtxtcountry;
    private javax.swing.JTextField jtxtdob;
    private javax.swing.JTextField jtxtfromAgeSearch;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtidClub;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtpos;
    private javax.swing.JTextField jtxtposInfo;
    private javax.swing.JTextField jtxtshortNameClub;
    private javax.swing.JTextField jtxttoAgeSearch;
    // End of variables declaration//GEN-END:variables
}
